kind: ConfigMap
apiVersion: v1
metadata:
  name: eureka-cm
data:
  eureka_service_address: http://eureka-0.eureka:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  clusterIP: None
  ports:
  - port: 8761
    name: eureka

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: regios1312/service-registry:0.0.2
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address

---

kind: Service
apiVersion: v1
metadata:
  name: eureka-lb
  labels:
   app: eureka
spec: 
  selector:
    app: eureka
  type: NodePort
  ports:
  - port: 80
    targetPort: 8761
